#pragma once


namespace Engine
{
	enum RENDERGROUP { RENDER_PRIORITY, RENDER_NONBLEND, RENDER_NONLIGHT, RENDER_NONLIGHT_BLOOM, RENDER_BLEND, RENDER_WORLD_UI, RENDER_BACK_UI, RENDER_UI, RENDER_BLEND_UI, RENDER_END };

	enum CLONE_TYPE {
		CLONE_ARGS,
		CLONE_FILEPATH,
		CLONE_END
	};

	enum CHANNELID {
		SOUND_EFFECT,
		SOUND_BGM,
		SOUND_PLAYER,
		SOUND_MONSTER,
		SOUND_UI,
		SOUND_UI_TEXTBOX,
		SOUND_STAGE_INFO,
		SOUND_STAGE_UI,
		SOUND_PLAYER_BULLET,
		SOUND_MONSTER_MOVE,
		SOUND_ITEM_GET1,
		SOUND_ITEM_GET2,
		SOUND_GET_DAMAGE_1,
		SOUND_GET_DAMAGE_2,
		SOUND_GET_DAMAGE_3,
		SOUND_GET_DAMAGE_4,
		SOUND_GET_DAMAGE_5,
		SOUND_GET_DAMAGE_6,
		SOUND_GET_DEBUFF0,
		SOUND_GET_DEBUFF1,
		SOUND_GET_DEBUFF2,
		SOUND_GET_DEBUFF3,
		SOUND_GET_BUFF,
		SOUND_SKILL_EFFECT0,
		SOUND_SKILL_EFFECT1,
		SOUND_SKILL_EFFECT2,
		SOUND_SKILL_EFFECT3,
		MAXCHANNEL
	};

}